### PR TITLE
Add mock data

### PR DESCRIPTION
**Pull request by nsylv**
Creates javascript files filled with mock data for animals, events, and people

TODO: generate HTML to display this mock data

### CODE REVIEW

**Comment by aluo-x** [comment]
Wait, was this intentionally a separate branch or is there some kind of permission issue?

**Comment by nsylv** [comment]
Answered on facebook but posting here as well:
Intentional - it's just the workflow I'm used to.  Shouldn't make a difference, but if it's confusing I can change to developing off of master

**Comment by aluo-x** [comment]
Looks good to me. Seems very robust

**Comment by nsylv** [comment]
Thanks - may have gone a little overkill just for mock data, but it was fun  :)

**Pull request merged**
